name: Release deliveries
on: 
  release:
    types: [published]

jobs:
  doc-publishing:
    name: Build sphinx documentation and publish on gh-page
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Checkout release tag  
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Deploy sphinx documentation
      uses: sphinx-notes/pages@v3

  pkg-publishing:
    name: Build package and publish on PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Checkout release tag  
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Install build dependencies
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
